---
title: "exo-spatial"
author: "Amaïa Lamarins"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##PRES

## ## install.packages("sf")
library("sf")
foix        <- c(1.6053807, 42.9638998)
carcassonne <- c(2.3491069, 43.2130358)
rodez       <- c(2.5728419, 44.3516207)
#convertit vecteurs en points spatiaux
foix        <- sf::st_point(foix)
carcassonne <- sf::st_point(carcassonne)
rodez       <- sf::st_point(rodez)
#regroupe en un seul spatial column en définissant le CRS
villes <- sf::st_sfc(
  list(foix, carcassonne, rodez),
  crs = 4326
)
class(villes)
#peut ajouter une table d'attributs 
datas <- data.frame(
  ville      = c("Foix", "Carcassonne", "Rodez"),
  population = c(9613, 45895, 23739)
)
villes <- sf::st_sf(datas, geom = villes)
class(villes)

#mais souvent importe direct data frame
## URL et nom du fichier
url      <- "https://raw.githubusercontent.com/FRBCesab/datatoolbox/master/data/"
filename <- "occitanie_prefectures.csv"
## Téléchargement du fichier
download.file(
  url      = paste0(url, filename),
  destfile = filename
)
## Extraction du ZIP
unzip(zipfile = filename)
## Ouverture du csv
(prefectures <- readr::read_csv("occitanie_prefectures.csv"))
#convertit en sf
prefectures <- sf::st_as_sf(
  x      = prefectures,
  coords = c("longitude", "latitude"),
  crs    = 4326
)
prefectures %>% head(6)

#carte
## install.packages("rnaturalearth")
## install.packages("rnaturalearthdata")
library("rnaturalearth")
library("rnaturalearthdata")
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
ggplot(data = world) +
  geom_sf() +
  xlab("Longitude") + ylab("Latitude") + ggtitle("Carte du monde")
ggplot(data = world) +
  geom_sf(fill = "#49847b", colour = "#e1ddc0") +
  xlab("Longitude") + ylab("Latitude") + ggtitle("Carte du monde") +
  geom_sf(data = prefectures, colour = "black")


#importer couche vectorielle
## URL et nom du fichier
url      <- "https://raw.githubusercontent.com/FRBCesab/datatoolbox/master/data/"
filename <- "occitanie.zip"
## Téléchargement du fichier
download.file(
  url      = paste0(url, filename),
  destfile = filename
)
## Extraction du ZIP
unzip(zipfile = filename)
sf::st_layers("occitanie.shp")
#importer couche
occitanie <- sf::st_read(dsn = ".", layer = "occitanie")
occitanie %>% head(3)
ggplot(data = occitanie) +
  geom_sf(fill = "#49847b", colour = "#e1ddc0") +
  xlab("Longitude") + ylab("Latitude") + ggtitle("OCCITANIE")
ggplot(data = occitanie) +
  geom_sf(fill = "#49847b", colour = "#e1ddc0") +
  xlab("Longitude") + ylab("Latitude") + ggtitle("OCCITANIE") +
  geom_sf(data = prefectures, colour = "#3f3f3f")
ggplot(data = occitanie) +
  geom_sf(fill = "#49847b", colour = "#e1ddc0") +
  xlab("Longitude") + ylab("Latitude") + ggtitle("OCCITANIE") +
  geom_sf(data = prefectures, colour = "#3f3f3f") +
  geom_sf_label(aes(label = NAME_2))
ggplot(data = occitanie) +
  geom_sf(fill = "#49847b", colour = "#e1ddc0") +
  xlab("Longitude") + ylab("Latitude") + ggtitle("OCCITANIE") +
  geom_sf(data = prefectures, colour = "#3f3f3f") +
  geom_sf_label(aes(label = paste0(NAME_2, " (", CC_2, ")")))
#exportation d'une couche vectorielle
sf::st_write(
  obj    = prefectures,
  dsn    = ".",
  layer  = "prefectures",
  driver = "ESRI Shapefile"
)
#peut aussi faire carte interactive avec catégories vite faites, avec mapview
#leaflet: mapview pour rmarkdown
#mapview exploration, leaflet production
```

